/* eslint-disable */
// AUTO-GENERATED by tokens/build-tokens.mjs — do not edit by hand.
// Run `node packages/ui/tokens/build-tokens.mjs` to regenerate.

export interface RampStep {
  step: number
  oklch: string
  hex: string
  contrast: { white: number; lightBg: number; darkBg: number }
  aaTextOnLight: boolean
  aaTextOnDark: boolean
}
export interface Ramp {
  name: string
  hue: number
  label: string
  role: string
  neutral: boolean
  steps: RampStep[]
}

export const RAMPS: Ramp[] = [
  {
    "name": "brand",
    "hue": 27,
    "label": "Brand · Coral",
    "role": "Primary action, brand signature",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0418 27)",
        "hex": "#fff0eb",
        "contrast": {
          "white": 1.11,
          "lightBg": 1.09,
          "darkBg": 16.32
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0646 27)",
        "hex": "#ffe3db",
        "contrast": {
          "white": 1.22,
          "lightBg": 1.2,
          "darkBg": 14.89
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.1064 27)",
        "hex": "#ffcabf",
        "contrast": {
          "white": 1.45,
          "lightBg": 1.43,
          "darkBg": 12.47
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1482 27)",
        "hex": "#ffaa9d",
        "contrast": {
          "white": 1.83,
          "lightBg": 1.8,
          "darkBg": 9.91
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1767 27)",
        "hex": "#ff8477",
        "contrast": {
          "white": 2.38,
          "lightBg": 2.34,
          "darkBg": 7.61
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.19 27)",
        "hex": "#fa6156",
        "contrast": {
          "white": 3.04,
          "lightBg": 2.99,
          "darkBg": 5.96
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1881 27)",
        "hex": "#de4840",
        "contrast": {
          "white": 4.11,
          "lightBg": 4.05,
          "darkBg": 4.41
        },
        "aaTextOnLight": false,
        "aaTextOnDark": false
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1748 27)",
        "hex": "#bc332f",
        "contrast": {
          "white": 5.75,
          "lightBg": 5.66,
          "darkBg": 3.15
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.152 27)",
        "hex": "#982421",
        "contrast": {
          "white": 8.05,
          "lightBg": 7.92,
          "darkBg": 2.25
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.1216 27)",
        "hex": "#711a17",
        "contrast": {
          "white": 11.28,
          "lightBg": 11.1,
          "darkBg": 1.61
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "amber",
    "hue": 68,
    "label": "Amber",
    "role": "Secondary / warm highlight",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0319 68)",
        "hex": "#fff7e4",
        "contrast": {
          "white": 1.07,
          "lightBg": 1.05,
          "darkBg": 16.97
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0493 68)",
        "hex": "#ffedd0",
        "contrast": {
          "white": 1.15,
          "lightBg": 1.13,
          "darkBg": 15.77
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.0812 68)",
        "hex": "#ffdcab",
        "contrast": {
          "white": 1.31,
          "lightBg": 1.29,
          "darkBg": 13.87
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1131 68)",
        "hex": "#ffc47f",
        "contrast": {
          "white": 1.56,
          "lightBg": 1.54,
          "darkBg": 11.61
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1348 68)",
        "hex": "#efa54d",
        "contrast": {
          "white": 2.07,
          "lightBg": 2.03,
          "darkBg": 8.76
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.145 68)",
        "hex": "#d48718",
        "contrast": {
          "white": 2.89,
          "lightBg": 2.84,
          "darkBg": 6.28
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1435 68)",
        "hex": "#bb7000",
        "contrast": {
          "white": 3.87,
          "lightBg": 3.81,
          "darkBg": 4.68
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1334 68)",
        "hex": "#9d5a00",
        "contrast": {
          "white": 5.39,
          "lightBg": 5.31,
          "darkBg": 3.36
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.116 68)",
        "hex": "#7e4600",
        "contrast": {
          "white": 7.6,
          "lightBg": 7.48,
          "darkBg": 2.38
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.0928 68)",
        "hex": "#5e3300",
        "contrast": {
          "white": 10.77,
          "lightBg": 10.6,
          "darkBg": 1.68
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "neutral",
    "hue": 72,
    "label": "Neutral · Warm",
    "role": "Text, surfaces, borders",
    "neutral": true,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.986 0.004 72)",
        "hex": "#fcfaf8",
        "contrast": {
          "white": 1.04,
          "lightBg": 1.02,
          "darkBg": 17.4
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.966 0.006 72)",
        "hex": "#f6f3ef",
        "contrast": {
          "white": 1.11,
          "lightBg": 1.09,
          "darkBg": 16.38
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.928 0.008 72)",
        "hex": "#ebe6e1",
        "contrast": {
          "white": 1.24,
          "lightBg": 1.22,
          "darkBg": 14.61
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.882 0.01 72)",
        "hex": "#dcd7d1",
        "contrast": {
          "white": 1.43,
          "lightBg": 1.41,
          "darkBg": 12.67
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.744 0.012 72)",
        "hex": "#b1aba4",
        "contrast": {
          "white": 2.28,
          "lightBg": 2.24,
          "darkBg": 7.96
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.606 0.014 72)",
        "hex": "#878179",
        "contrast": {
          "white": 3.86,
          "lightBg": 3.8,
          "darkBg": 4.7
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.5 0.014 72)",
        "hex": "#68625b",
        "contrast": {
          "white": 6.02,
          "lightBg": 5.93,
          "darkBg": 3.01
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 700,
        "oklch": "oklch(0.412 0.014 72)",
        "hex": "#504a43",
        "contrast": {
          "white": 8.74,
          "lightBg": 8.61,
          "darkBg": 2.07
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.312 0.016 72)",
        "hex": "#363028",
        "contrast": {
          "white": 13.04,
          "lightBg": 12.84,
          "darkBg": 1.39
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.224 0.018 72)",
        "hex": "#211a12",
        "contrast": {
          "white": 17.2,
          "lightBg": 16.93,
          "darkBg": 1.05
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "success",
    "hue": 150,
    "label": "Success · Green",
    "role": "Positive / paid / done",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.033 150)",
        "hex": "#ebffef",
        "contrast": {
          "white": 1.05,
          "lightBg": 1.03,
          "darkBg": 17.32
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.051 150)",
        "hex": "#dbfde1",
        "contrast": {
          "white": 1.1,
          "lightBg": 1.08,
          "darkBg": 16.52
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.084 150)",
        "hex": "#bef6c8",
        "contrast": {
          "white": 1.22,
          "lightBg": 1.2,
          "darkBg": 14.84
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.117 150)",
        "hex": "#99e8a9",
        "contrast": {
          "white": 1.45,
          "lightBg": 1.43,
          "darkBg": 12.48
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1395 150)",
        "hex": "#6fd086",
        "contrast": {
          "white": 1.9,
          "lightBg": 1.87,
          "darkBg": 9.53
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.15 150)",
        "hex": "#48b467",
        "contrast": {
          "white": 2.63,
          "lightBg": 2.58,
          "darkBg": 6.9
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1485 150)",
        "hex": "#2d9c51",
        "contrast": {
          "white": 3.51,
          "lightBg": 3.45,
          "darkBg": 5.16
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.138 150)",
        "hex": "#16823e",
        "contrast": {
          "white": 4.89,
          "lightBg": 4.81,
          "darkBg": 3.71
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.12 150)",
        "hex": "#09672e",
        "contrast": {
          "white": 7.02,
          "lightBg": 6.91,
          "darkBg": 2.58
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.096 150)",
        "hex": "#074c21",
        "contrast": {
          "white": 10.17,
          "lightBg": 10.01,
          "darkBg": 1.78
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "warning",
    "hue": 85,
    "label": "Warning · Gold",
    "role": "Caution / due soon",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0363 85)",
        "hex": "#fff9df",
        "contrast": {
          "white": 1.06,
          "lightBg": 1.04,
          "darkBg": 17.14
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0561 85)",
        "hex": "#fff0c8",
        "contrast": {
          "white": 1.13,
          "lightBg": 1.11,
          "darkBg": 16
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.0924 85)",
        "hex": "#ffe19d",
        "contrast": {
          "white": 1.27,
          "lightBg": 1.25,
          "darkBg": 14.24
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1287 85)",
        "hex": "#f9cb68",
        "contrast": {
          "white": 1.53,
          "lightBg": 1.5,
          "darkBg": 11.88
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1535 85)",
        "hex": "#e3ad1e",
        "contrast": {
          "white": 2.05,
          "lightBg": 2.01,
          "darkBg": 8.85
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.165 85)",
        "hex": "#c99000",
        "contrast": {
          "white": 2.81,
          "lightBg": 2.77,
          "darkBg": 6.45
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1633 85)",
        "hex": "#b07800",
        "contrast": {
          "white": 3.8,
          "lightBg": 3.74,
          "darkBg": 4.77
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1518 85)",
        "hex": "#946200",
        "contrast": {
          "white": 5.24,
          "lightBg": 5.16,
          "darkBg": 3.46
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.132 85)",
        "hex": "#764c00",
        "contrast": {
          "white": 7.49,
          "lightBg": 7.37,
          "darkBg": 2.42
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.1056 85)",
        "hex": "#583800",
        "contrast": {
          "white": 10.6,
          "lightBg": 10.44,
          "darkBg": 1.71
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "error",
    "hue": 18,
    "label": "Error · Red",
    "role": "Destructive / overdue",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0451 18)",
        "hex": "#ffefef",
        "contrast": {
          "white": 1.11,
          "lightBg": 1.1,
          "darkBg": 16.26
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0697 18)",
        "hex": "#ffe0e1",
        "contrast": {
          "white": 1.24,
          "lightBg": 1.22,
          "darkBg": 14.67
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.1148 18)",
        "hex": "#ffc6c8",
        "contrast": {
          "white": 1.48,
          "lightBg": 1.46,
          "darkBg": 12.22
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1599 18)",
        "hex": "#ffa4aa",
        "contrast": {
          "white": 1.88,
          "lightBg": 1.86,
          "darkBg": 9.61
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1906 18)",
        "hex": "#ff7b88",
        "contrast": {
          "white": 2.49,
          "lightBg": 2.45,
          "darkBg": 7.28
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.205 18)",
        "hex": "#ff5669",
        "contrast": {
          "white": 3.09,
          "lightBg": 3.05,
          "darkBg": 5.85
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.2029 18)",
        "hex": "#e33b53",
        "contrast": {
          "white": 4.19,
          "lightBg": 4.12,
          "darkBg": 4.33
        },
        "aaTextOnLight": false,
        "aaTextOnDark": false
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1886 18)",
        "hex": "#c12641",
        "contrast": {
          "white": 5.8,
          "lightBg": 5.71,
          "darkBg": 3.12
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.164 18)",
        "hex": "#9c1831",
        "contrast": {
          "white": 8.11,
          "lightBg": 7.99,
          "darkBg": 2.23
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.1312 18)",
        "hex": "#741223",
        "contrast": {
          "white": 11.33,
          "lightBg": 11.15,
          "darkBg": 1.6
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "info",
    "hue": 245,
    "label": "Info · Blue",
    "role": "Informational / calendar",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0308 245)",
        "hex": "#eafdff",
        "contrast": {
          "white": 1.05,
          "lightBg": 1.03,
          "darkBg": 17.25
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0476 245)",
        "hex": "#d9f7ff",
        "contrast": {
          "white": 1.12,
          "lightBg": 1.11,
          "darkBg": 16.13
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.0784 245)",
        "hex": "#baecff",
        "contrast": {
          "white": 1.27,
          "lightBg": 1.25,
          "darkBg": 14.26
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1092 245)",
        "hex": "#94daff",
        "contrast": {
          "white": 1.53,
          "lightBg": 1.51,
          "darkBg": 11.85
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1302 245)",
        "hex": "#69bfff",
        "contrast": {
          "white": 2,
          "lightBg": 1.97,
          "darkBg": 9.05
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.14 245)",
        "hex": "#42a2eb",
        "contrast": {
          "white": 2.76,
          "lightBg": 2.72,
          "darkBg": 6.56
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1386 245)",
        "hex": "#268ad1",
        "contrast": {
          "white": 3.72,
          "lightBg": 3.67,
          "darkBg": 4.86
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1288 245)",
        "hex": "#0f72b1",
        "contrast": {
          "white": 5.17,
          "lightBg": 5.09,
          "darkBg": 3.5
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.112 245)",
        "hex": "#03598f",
        "contrast": {
          "white": 7.42,
          "lightBg": 7.31,
          "darkBg": 2.44
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.0896 245)",
        "hex": "#04426a",
        "contrast": {
          "white": 10.54,
          "lightBg": 10.37,
          "darkBg": 1.72
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "ai",
    "hue": 300,
    "label": "AI · Violet",
    "role": "AI-generated marker (reserve it)",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0407 300)",
        "hex": "#fef5ff",
        "contrast": {
          "white": 1.06,
          "lightBg": 1.05,
          "darkBg": 17.01
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0629 300)",
        "hex": "#f9eaff",
        "contrast": {
          "white": 1.15,
          "lightBg": 1.13,
          "darkBg": 15.73
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.1036 300)",
        "hex": "#f0d6ff",
        "contrast": {
          "white": 1.33,
          "lightBg": 1.31,
          "darkBg": 13.6
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1443 300)",
        "hex": "#e1bcff",
        "contrast": {
          "white": 1.64,
          "lightBg": 1.61,
          "darkBg": 11.07
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1721 300)",
        "hex": "#c89aff",
        "contrast": {
          "white": 2.21,
          "lightBg": 2.17,
          "darkBg": 8.21
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.185 300)",
        "hex": "#ae7bfa",
        "contrast": {
          "white": 2.99,
          "lightBg": 2.95,
          "darkBg": 6.05
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1832 300)",
        "hex": "#9663df",
        "contrast": {
          "white": 4.08,
          "lightBg": 4.02,
          "darkBg": 4.44
        },
        "aaTextOnLight": false,
        "aaTextOnDark": false
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1702 300)",
        "hex": "#7d4ebe",
        "contrast": {
          "white": 5.67,
          "lightBg": 5.58,
          "darkBg": 3.2
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.148 300)",
        "hex": "#633c9a",
        "contrast": {
          "white": 7.94,
          "lightBg": 7.82,
          "darkBg": 2.28
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.1184 300)",
        "hex": "#492b73",
        "contrast": {
          "white": 11.19,
          "lightBg": 11.02,
          "darkBg": 1.62
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  }
]

export const SPACE_SCALE: { key: string; px: number }[] = [
  {
    "key": "0",
    "px": 0
  },
  {
    "key": "1",
    "px": 4
  },
  {
    "key": "2",
    "px": 8
  },
  {
    "key": "3",
    "px": 12
  },
  {
    "key": "4",
    "px": 16
  },
  {
    "key": "5",
    "px": 20
  },
  {
    "key": "6",
    "px": 24
  },
  {
    "key": "8",
    "px": 32
  },
  {
    "key": "10",
    "px": 40
  },
  {
    "key": "12",
    "px": 48
  },
  {
    "key": "16",
    "px": 64
  },
  {
    "key": "20",
    "px": 80
  },
  {
    "key": "24",
    "px": 96
  }
]
export const SPACE_ALIASES: { alias: string; key: string; px: number }[] = [
  {
    "alias": "3xs",
    "key": "1",
    "px": 4
  },
  {
    "alias": "2xs",
    "key": "2",
    "px": 8
  },
  {
    "alias": "xs",
    "key": "3",
    "px": 12
  },
  {
    "alias": "sm",
    "key": "4",
    "px": 16
  },
  {
    "alias": "md",
    "key": "6",
    "px": 24
  },
  {
    "alias": "lg",
    "key": "8",
    "px": 32
  },
  {
    "alias": "xl",
    "key": "12",
    "px": 48
  },
  {
    "alias": "2xl",
    "key": "16",
    "px": 64
  },
  {
    "alias": "3xl",
    "key": "24",
    "px": 96
  }
]
export const RADIUS_SCALE: { key: string; px: number }[] = [
  {
    "key": "sm",
    "px": 4
  },
  {
    "key": "md",
    "px": 6
  },
  {
    "key": "lg",
    "px": 8
  },
  {
    "key": "xl",
    "px": 10
  },
  {
    "key": "2xl",
    "px": 14
  },
  {
    "key": "3xl",
    "px": 20
  },
  {
    "key": "full",
    "px": 9999
  }
]
export const TYPE_SCALE: { key: string; size: number; line: number; weight: number; tracking: number; use: string; display: boolean }[] = [
  {
    "key": "2xs",
    "size": 11,
    "line": 16,
    "weight": 500,
    "tracking": 0.2,
    "use": "meta, badges, kbd",
    "display": false
  },
  {
    "key": "xs",
    "size": 12,
    "line": 16,
    "weight": 400,
    "tracking": 0,
    "use": "dense labels, chips",
    "display": false
  },
  {
    "key": "sm",
    "size": 14,
    "line": 20,
    "weight": 400,
    "tracking": 0,
    "use": "secondary / supporting body",
    "display": false
  },
  {
    "key": "base",
    "size": 16,
    "line": 24,
    "weight": 400,
    "tracking": 0,
    "use": "body",
    "display": false
  },
  {
    "key": "lg",
    "size": 18,
    "line": 28,
    "weight": 500,
    "tracking": -0.1,
    "use": "lead paragraph, list titles",
    "display": false
  },
  {
    "key": "xl",
    "size": 20,
    "line": 28,
    "weight": 600,
    "tracking": -0.2,
    "use": "section heading (sans)",
    "display": false
  },
  {
    "key": "2xl",
    "size": 24,
    "line": 32,
    "weight": 600,
    "tracking": -0.3,
    "use": "card / panel title",
    "display": false
  },
  {
    "key": "display-sm",
    "size": 30,
    "line": 36,
    "weight": 600,
    "tracking": -0.4,
    "use": "screen title (Fraunces)",
    "display": true
  },
  {
    "key": "display-md",
    "size": 38,
    "line": 44,
    "weight": 600,
    "tracking": -0.5,
    "use": "greeting (Fraunces)",
    "display": true
  },
  {
    "key": "display-lg",
    "size": 52,
    "line": 56,
    "weight": 600,
    "tracking": -1,
    "use": "hero (Fraunces)",
    "display": true
  }
]
export const CONTRAST_REPORT = {
  "reference": {
    "lightBg": "#fffdf9",
    "darkBg": "#1a1511",
    "white": "#ffffff"
  },
  "standard": "WCAG 2.1 — AA 4.5 (normal), 3.0 (large), AAA 7.0",
  "pairs": [
    {
      "label": "primary label — neutral.50 on brand.700",
      "on": "primary button (light)",
      "fg": "#fcfaf8",
      "bg": "#bc332f",
      "ratio": 5.52,
      "grade": "AA"
    },
    {
      "label": "primary label — neutral.900 on brand.500",
      "on": "primary button (dark)",
      "fg": "#211a12",
      "bg": "#fa6156",
      "ratio": 5.66,
      "grade": "AA"
    },
    {
      "label": "text.primary — neutral.900",
      "on": "light canvas",
      "fg": "#211a12",
      "bg": "#fffdf9",
      "ratio": 16.93,
      "grade": "AAA"
    },
    {
      "label": "text.secondary — neutral.700",
      "on": "light canvas",
      "fg": "#504a43",
      "bg": "#fffdf9",
      "ratio": 8.61,
      "grade": "AAA"
    },
    {
      "label": "text.muted — neutral.600",
      "on": "light canvas",
      "fg": "#68625b",
      "bg": "#fffdf9",
      "ratio": 5.93,
      "grade": "AA"
    },
    {
      "label": "text.secondary dark — neutral.300",
      "on": "dark canvas",
      "fg": "#dcd7d1",
      "bg": "#1a1511",
      "ratio": 12.67,
      "grade": "AAA"
    },
    {
      "label": "action.quietText — brand.700 on brand.100",
      "on": "quiet chip",
      "fg": "#bc332f",
      "bg": "#ffe3db",
      "ratio": 4.73,
      "grade": "AA"
    },
    {
      "label": "error.700 text",
      "on": "light canvas",
      "fg": "#c12641",
      "bg": "#fffdf9",
      "ratio": 5.71,
      "grade": "AA"
    },
    {
      "label": "success.700 text",
      "on": "light canvas",
      "fg": "#16823e",
      "bg": "#fffdf9",
      "ratio": 4.81,
      "grade": "AA"
    },
    {
      "label": "warning.800 text",
      "on": "light canvas",
      "fg": "#764c00",
      "bg": "#fffdf9",
      "ratio": 7.37,
      "grade": "AAA"
    },
    {
      "label": "info.700 text",
      "on": "light canvas",
      "fg": "#0f72b1",
      "bg": "#fffdf9",
      "ratio": 5.09,
      "grade": "AA"
    },
    {
      "label": "ai.700 text",
      "on": "light canvas",
      "fg": "#7d4ebe",
      "bg": "#fffdf9",
      "ratio": 5.58,
      "grade": "AA"
    }
  ],
  "ramps": {
    "brand": [
      {
        "step": 50,
        "hex": "#fff0eb",
        "onLight": 1.09,
        "onDark": 16.32
      },
      {
        "step": 100,
        "hex": "#ffe3db",
        "onLight": 1.2,
        "onDark": 14.89
      },
      {
        "step": 200,
        "hex": "#ffcabf",
        "onLight": 1.43,
        "onDark": 12.47
      },
      {
        "step": 300,
        "hex": "#ffaa9d",
        "onLight": 1.8,
        "onDark": 9.91
      },
      {
        "step": 400,
        "hex": "#ff8477",
        "onLight": 2.34,
        "onDark": 7.61
      },
      {
        "step": 500,
        "hex": "#fa6156",
        "onLight": 2.99,
        "onDark": 5.96
      },
      {
        "step": 600,
        "hex": "#de4840",
        "onLight": 4.05,
        "onDark": 4.41
      },
      {
        "step": 700,
        "hex": "#bc332f",
        "onLight": 5.66,
        "onDark": 3.15
      },
      {
        "step": 800,
        "hex": "#982421",
        "onLight": 7.92,
        "onDark": 2.25
      },
      {
        "step": 900,
        "hex": "#711a17",
        "onLight": 11.1,
        "onDark": 1.61
      }
    ],
    "amber": [
      {
        "step": 50,
        "hex": "#fff7e4",
        "onLight": 1.05,
        "onDark": 16.97
      },
      {
        "step": 100,
        "hex": "#ffedd0",
        "onLight": 1.13,
        "onDark": 15.77
      },
      {
        "step": 200,
        "hex": "#ffdcab",
        "onLight": 1.29,
        "onDark": 13.87
      },
      {
        "step": 300,
        "hex": "#ffc47f",
        "onLight": 1.54,
        "onDark": 11.61
      },
      {
        "step": 400,
        "hex": "#efa54d",
        "onLight": 2.03,
        "onDark": 8.76
      },
      {
        "step": 500,
        "hex": "#d48718",
        "onLight": 2.84,
        "onDark": 6.28
      },
      {
        "step": 600,
        "hex": "#bb7000",
        "onLight": 3.81,
        "onDark": 4.68
      },
      {
        "step": 700,
        "hex": "#9d5a00",
        "onLight": 5.31,
        "onDark": 3.36
      },
      {
        "step": 800,
        "hex": "#7e4600",
        "onLight": 7.48,
        "onDark": 2.38
      },
      {
        "step": 900,
        "hex": "#5e3300",
        "onLight": 10.6,
        "onDark": 1.68
      }
    ],
    "neutral": [
      {
        "step": 50,
        "hex": "#fcfaf8",
        "onLight": 1.02,
        "onDark": 17.4
      },
      {
        "step": 100,
        "hex": "#f6f3ef",
        "onLight": 1.09,
        "onDark": 16.38
      },
      {
        "step": 200,
        "hex": "#ebe6e1",
        "onLight": 1.22,
        "onDark": 14.61
      },
      {
        "step": 300,
        "hex": "#dcd7d1",
        "onLight": 1.41,
        "onDark": 12.67
      },
      {
        "step": 400,
        "hex": "#b1aba4",
        "onLight": 2.24,
        "onDark": 7.96
      },
      {
        "step": 500,
        "hex": "#878179",
        "onLight": 3.8,
        "onDark": 4.7
      },
      {
        "step": 600,
        "hex": "#68625b",
        "onLight": 5.93,
        "onDark": 3.01
      },
      {
        "step": 700,
        "hex": "#504a43",
        "onLight": 8.61,
        "onDark": 2.07
      },
      {
        "step": 800,
        "hex": "#363028",
        "onLight": 12.84,
        "onDark": 1.39
      },
      {
        "step": 900,
        "hex": "#211a12",
        "onLight": 16.93,
        "onDark": 1.05
      }
    ],
    "success": [
      {
        "step": 50,
        "hex": "#ebffef",
        "onLight": 1.03,
        "onDark": 17.32
      },
      {
        "step": 100,
        "hex": "#dbfde1",
        "onLight": 1.08,
        "onDark": 16.52
      },
      {
        "step": 200,
        "hex": "#bef6c8",
        "onLight": 1.2,
        "onDark": 14.84
      },
      {
        "step": 300,
        "hex": "#99e8a9",
        "onLight": 1.43,
        "onDark": 12.48
      },
      {
        "step": 400,
        "hex": "#6fd086",
        "onLight": 1.87,
        "onDark": 9.53
      },
      {
        "step": 500,
        "hex": "#48b467",
        "onLight": 2.58,
        "onDark": 6.9
      },
      {
        "step": 600,
        "hex": "#2d9c51",
        "onLight": 3.45,
        "onDark": 5.16
      },
      {
        "step": 700,
        "hex": "#16823e",
        "onLight": 4.81,
        "onDark": 3.71
      },
      {
        "step": 800,
        "hex": "#09672e",
        "onLight": 6.91,
        "onDark": 2.58
      },
      {
        "step": 900,
        "hex": "#074c21",
        "onLight": 10.01,
        "onDark": 1.78
      }
    ],
    "warning": [
      {
        "step": 50,
        "hex": "#fff9df",
        "onLight": 1.04,
        "onDark": 17.14
      },
      {
        "step": 100,
        "hex": "#fff0c8",
        "onLight": 1.11,
        "onDark": 16
      },
      {
        "step": 200,
        "hex": "#ffe19d",
        "onLight": 1.25,
        "onDark": 14.24
      },
      {
        "step": 300,
        "hex": "#f9cb68",
        "onLight": 1.5,
        "onDark": 11.88
      },
      {
        "step": 400,
        "hex": "#e3ad1e",
        "onLight": 2.01,
        "onDark": 8.85
      },
      {
        "step": 500,
        "hex": "#c99000",
        "onLight": 2.77,
        "onDark": 6.45
      },
      {
        "step": 600,
        "hex": "#b07800",
        "onLight": 3.74,
        "onDark": 4.77
      },
      {
        "step": 700,
        "hex": "#946200",
        "onLight": 5.16,
        "onDark": 3.46
      },
      {
        "step": 800,
        "hex": "#764c00",
        "onLight": 7.37,
        "onDark": 2.42
      },
      {
        "step": 900,
        "hex": "#583800",
        "onLight": 10.44,
        "onDark": 1.71
      }
    ],
    "error": [
      {
        "step": 50,
        "hex": "#ffefef",
        "onLight": 1.1,
        "onDark": 16.26
      },
      {
        "step": 100,
        "hex": "#ffe0e1",
        "onLight": 1.22,
        "onDark": 14.67
      },
      {
        "step": 200,
        "hex": "#ffc6c8",
        "onLight": 1.46,
        "onDark": 12.22
      },
      {
        "step": 300,
        "hex": "#ffa4aa",
        "onLight": 1.86,
        "onDark": 9.61
      },
      {
        "step": 400,
        "hex": "#ff7b88",
        "onLight": 2.45,
        "onDark": 7.28
      },
      {
        "step": 500,
        "hex": "#ff5669",
        "onLight": 3.05,
        "onDark": 5.85
      },
      {
        "step": 600,
        "hex": "#e33b53",
        "onLight": 4.12,
        "onDark": 4.33
      },
      {
        "step": 700,
        "hex": "#c12641",
        "onLight": 5.71,
        "onDark": 3.12
      },
      {
        "step": 800,
        "hex": "#9c1831",
        "onLight": 7.99,
        "onDark": 2.23
      },
      {
        "step": 900,
        "hex": "#741223",
        "onLight": 11.15,
        "onDark": 1.6
      }
    ],
    "info": [
      {
        "step": 50,
        "hex": "#eafdff",
        "onLight": 1.03,
        "onDark": 17.25
      },
      {
        "step": 100,
        "hex": "#d9f7ff",
        "onLight": 1.11,
        "onDark": 16.13
      },
      {
        "step": 200,
        "hex": "#baecff",
        "onLight": 1.25,
        "onDark": 14.26
      },
      {
        "step": 300,
        "hex": "#94daff",
        "onLight": 1.51,
        "onDark": 11.85
      },
      {
        "step": 400,
        "hex": "#69bfff",
        "onLight": 1.97,
        "onDark": 9.05
      },
      {
        "step": 500,
        "hex": "#42a2eb",
        "onLight": 2.72,
        "onDark": 6.56
      },
      {
        "step": 600,
        "hex": "#268ad1",
        "onLight": 3.67,
        "onDark": 4.86
      },
      {
        "step": 700,
        "hex": "#0f72b1",
        "onLight": 5.09,
        "onDark": 3.5
      },
      {
        "step": 800,
        "hex": "#03598f",
        "onLight": 7.31,
        "onDark": 2.44
      },
      {
        "step": 900,
        "hex": "#04426a",
        "onLight": 10.37,
        "onDark": 1.72
      }
    ],
    "ai": [
      {
        "step": 50,
        "hex": "#fef5ff",
        "onLight": 1.05,
        "onDark": 17.01
      },
      {
        "step": 100,
        "hex": "#f9eaff",
        "onLight": 1.13,
        "onDark": 15.73
      },
      {
        "step": 200,
        "hex": "#f0d6ff",
        "onLight": 1.31,
        "onDark": 13.6
      },
      {
        "step": 300,
        "hex": "#e1bcff",
        "onLight": 1.61,
        "onDark": 11.07
      },
      {
        "step": 400,
        "hex": "#c89aff",
        "onLight": 2.17,
        "onDark": 8.21
      },
      {
        "step": 500,
        "hex": "#ae7bfa",
        "onLight": 2.95,
        "onDark": 6.05
      },
      {
        "step": 600,
        "hex": "#9663df",
        "onLight": 4.02,
        "onDark": 4.44
      },
      {
        "step": 700,
        "hex": "#7d4ebe",
        "onLight": 5.58,
        "onDark": 3.2
      },
      {
        "step": 800,
        "hex": "#633c9a",
        "onLight": 7.82,
        "onDark": 2.28
      },
      {
        "step": 900,
        "hex": "#492b73",
        "onLight": 11.02,
        "onDark": 1.62
      }
    ]
  }
} as const

