/* eslint-disable */
// AUTO-GENERATED by tokens/build-tokens.mjs — do not edit by hand.
// Run `node packages/ui/tokens/build-tokens.mjs` to regenerate.

export interface RampStep {
  step: number
  oklch: string
  hex: string
  contrast: { white: number; lightBg: number; darkBg: number }
  aaTextOnLight: boolean
  aaTextOnDark: boolean
}
export interface Ramp {
  name: string
  hue: number
  label: string
  role: string
  neutral: boolean
  steps: RampStep[]
}

export const RAMPS: Ramp[] = [
  {
    "name": "neutral",
    "hue": 255,
    "label": "Neutral · Ink → Paper",
    "role": "Text, surfaces, borders — ~the entire UI",
    "neutral": true,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.002 255)",
        "hex": "#f9fafb",
        "contrast": {
          "white": 1.05,
          "lightBg": 1,
          "darkBg": 17.18
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.965 0.003 255)",
        "hex": "#f2f3f5",
        "contrast": {
          "white": 1.11,
          "lightBg": 1.06,
          "darkBg": 16.17
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.926 0.004 255)",
        "hex": "#e5e7e9",
        "contrast": {
          "white": 1.24,
          "lightBg": 1.19,
          "darkBg": 14.49
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.876 0.005 255)",
        "hex": "#d4d6d9",
        "contrast": {
          "white": 1.46,
          "lightBg": 1.39,
          "darkBg": 12.33
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.735 0.006 255)",
        "hex": "#a7a9ad",
        "contrast": {
          "white": 2.35,
          "lightBg": 2.25,
          "darkBg": 7.63
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.598 0.006 255)",
        "hex": "#7d8083",
        "contrast": {
          "white": 3.97,
          "lightBg": 3.8,
          "darkBg": 4.52
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.492 0.007 255)",
        "hex": "#5e6165",
        "contrast": {
          "white": 6.22,
          "lightBg": 5.95,
          "darkBg": 2.89
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 700,
        "oklch": "oklch(0.4 0.008 255)",
        "hex": "#45484c",
        "contrast": {
          "white": 9.19,
          "lightBg": 8.79,
          "darkBg": 1.95
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.3 0.008 255)",
        "hex": "#2b2e32",
        "contrast": {
          "white": 13.64,
          "lightBg": 13.05,
          "darkBg": 1.32
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.205 0.01 255)",
        "hex": "#14171c",
        "contrast": {
          "white": 17.96,
          "lightBg": 17.18,
          "darkBg": 1
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "accent",
    "hue": 255,
    "label": "Accent · Dark Blue",
    "role": "Sparingly: links, focus, selected, AI marker",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0308 255)",
        "hex": "#edfcff",
        "contrast": {
          "white": 1.05,
          "lightBg": 1.01,
          "darkBg": 17.08
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0476 255)",
        "hex": "#def5ff",
        "contrast": {
          "white": 1.13,
          "lightBg": 1.08,
          "darkBg": 15.92
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.0784 255)",
        "hex": "#c3e9ff",
        "contrast": {
          "white": 1.28,
          "lightBg": 1.22,
          "darkBg": 14.04
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1092 255)",
        "hex": "#a1d6ff",
        "contrast": {
          "white": 1.55,
          "lightBg": 1.48,
          "darkBg": 11.61
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1302 255)",
        "hex": "#7cbaff",
        "contrast": {
          "white": 2.03,
          "lightBg": 1.95,
          "darkBg": 8.83
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.14 255)",
        "hex": "#5b9def",
        "contrast": {
          "white": 2.79,
          "lightBg": 2.67,
          "darkBg": 6.43
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1386 255)",
        "hex": "#4585d5",
        "contrast": {
          "white": 3.77,
          "lightBg": 3.61,
          "darkBg": 4.76
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1288 255)",
        "hex": "#326db5",
        "contrast": {
          "white": 5.26,
          "lightBg": 5.03,
          "darkBg": 3.41
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.112 255)",
        "hex": "#245692",
        "contrast": {
          "white": 7.44,
          "lightBg": 7.12,
          "darkBg": 2.41
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.0896 255)",
        "hex": "#1a3f6d",
        "contrast": {
          "white": 10.63,
          "lightBg": 10.17,
          "darkBg": 1.69
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  },
  {
    "name": "danger",
    "hue": 25,
    "label": "Danger · Red",
    "role": "Destructive / overdue — the one retained hue",
    "neutral": false,
    "steps": [
      {
        "step": 50,
        "oklch": "oklch(0.985 0.0297 25)",
        "hex": "#fff3f0",
        "contrast": {
          "white": 1.09,
          "lightBg": 1.04,
          "darkBg": 16.53
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 100,
        "oklch": "oklch(0.962 0.0459 25)",
        "hex": "#ffe7e3",
        "contrast": {
          "white": 1.18,
          "lightBg": 1.13,
          "darkBg": 15.21
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 200,
        "oklch": "oklch(0.922 0.0756 25)",
        "hex": "#ffd2cc",
        "contrast": {
          "white": 1.37,
          "lightBg": 1.31,
          "darkBg": 13.12
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 300,
        "oklch": "oklch(0.864 0.1053 25)",
        "hex": "#ffb7af",
        "contrast": {
          "white": 1.66,
          "lightBg": 1.59,
          "darkBg": 10.81
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 400,
        "oklch": "oklch(0.778 0.1256 25)",
        "hex": "#fd968e",
        "contrast": {
          "white": 2.11,
          "lightBg": 2.02,
          "darkBg": 8.49
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 500,
        "oklch": "oklch(0.688 0.135 25)",
        "hex": "#e2766f",
        "contrast": {
          "white": 2.98,
          "lightBg": 2.85,
          "darkBg": 6.03
        },
        "aaTextOnLight": false,
        "aaTextOnDark": true
      },
      {
        "step": 600,
        "oklch": "oklch(0.612 0.1337 25)",
        "hex": "#c7605a",
        "contrast": {
          "white": 4,
          "lightBg": 3.83,
          "darkBg": 4.49
        },
        "aaTextOnLight": false,
        "aaTextOnDark": false
      },
      {
        "step": 700,
        "oklch": "oklch(0.532 0.1242 25)",
        "hex": "#a84b46",
        "contrast": {
          "white": 5.59,
          "lightBg": 5.34,
          "darkBg": 3.22
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 800,
        "oklch": "oklch(0.45 0.108 25)",
        "hex": "#873936",
        "contrast": {
          "white": 7.87,
          "lightBg": 7.53,
          "darkBg": 2.28
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      },
      {
        "step": 900,
        "oklch": "oklch(0.366 0.0864 25)",
        "hex": "#652927",
        "contrast": {
          "white": 11.05,
          "lightBg": 10.57,
          "darkBg": 1.62
        },
        "aaTextOnLight": true,
        "aaTextOnDark": false
      }
    ]
  }
]

export const SPACE_SCALE: { key: string; px: number }[] = [
  {
    "key": "0",
    "px": 0
  },
  {
    "key": "1",
    "px": 4
  },
  {
    "key": "2",
    "px": 8
  },
  {
    "key": "3",
    "px": 12
  },
  {
    "key": "4",
    "px": 16
  },
  {
    "key": "5",
    "px": 20
  },
  {
    "key": "6",
    "px": 24
  },
  {
    "key": "8",
    "px": 32
  },
  {
    "key": "10",
    "px": 40
  },
  {
    "key": "12",
    "px": 48
  },
  {
    "key": "16",
    "px": 64
  },
  {
    "key": "20",
    "px": 80
  },
  {
    "key": "24",
    "px": 96
  }
]
export const SPACE_ALIASES: { alias: string; key: string; px: number }[] = [
  {
    "alias": "3xs",
    "key": "1",
    "px": 4
  },
  {
    "alias": "2xs",
    "key": "2",
    "px": 8
  },
  {
    "alias": "xs",
    "key": "3",
    "px": 12
  },
  {
    "alias": "sm",
    "key": "4",
    "px": 16
  },
  {
    "alias": "md",
    "key": "6",
    "px": 24
  },
  {
    "alias": "lg",
    "key": "8",
    "px": 32
  },
  {
    "alias": "xl",
    "key": "12",
    "px": 48
  },
  {
    "alias": "2xl",
    "key": "16",
    "px": 64
  },
  {
    "alias": "3xl",
    "key": "24",
    "px": 96
  }
]
export const RADIUS_SCALE: { key: string; px: number }[] = [
  {
    "key": "sm",
    "px": 4
  },
  {
    "key": "md",
    "px": 6
  },
  {
    "key": "lg",
    "px": 8
  },
  {
    "key": "xl",
    "px": 10
  },
  {
    "key": "2xl",
    "px": 14
  },
  {
    "key": "3xl",
    "px": 20
  },
  {
    "key": "full",
    "px": 9999
  }
]
export const TYPE_SCALE: { key: string; size: number; line: number; weight: number; tracking: number; use: string; display: boolean }[] = [
  {
    "key": "2xs",
    "size": 11,
    "line": 16,
    "weight": 500,
    "tracking": 0.2,
    "use": "meta, badges, kbd",
    "display": false
  },
  {
    "key": "xs",
    "size": 12,
    "line": 16,
    "weight": 400,
    "tracking": 0,
    "use": "dense labels, chips",
    "display": false
  },
  {
    "key": "sm",
    "size": 14,
    "line": 20,
    "weight": 400,
    "tracking": 0,
    "use": "secondary / supporting body",
    "display": false
  },
  {
    "key": "base",
    "size": 16,
    "line": 24,
    "weight": 400,
    "tracking": 0,
    "use": "body",
    "display": false
  },
  {
    "key": "lg",
    "size": 18,
    "line": 28,
    "weight": 500,
    "tracking": -0.1,
    "use": "lead paragraph, list titles",
    "display": false
  },
  {
    "key": "xl",
    "size": 20,
    "line": 28,
    "weight": 600,
    "tracking": -0.2,
    "use": "section heading (sans)",
    "display": false
  },
  {
    "key": "2xl",
    "size": 24,
    "line": 32,
    "weight": 600,
    "tracking": -0.3,
    "use": "card / panel title",
    "display": false
  },
  {
    "key": "display-sm",
    "size": 30,
    "line": 36,
    "weight": 600,
    "tracking": -0.4,
    "use": "screen title (Fraunces)",
    "display": true
  },
  {
    "key": "display-md",
    "size": 38,
    "line": 44,
    "weight": 600,
    "tracking": -0.5,
    "use": "greeting (Fraunces)",
    "display": true
  },
  {
    "key": "display-lg",
    "size": 52,
    "line": 56,
    "weight": 600,
    "tracking": -1,
    "use": "hero (Fraunces)",
    "display": true
  }
]
export const CONTRAST_REPORT = {
  "reference": {
    "lightBg": "#f8fafd",
    "darkBg": "#15171a",
    "white": "#ffffff"
  },
  "standard": "WCAG 2.1 — AA 4.5 (normal), 3.0 (large), AAA 7.0",
  "pairs": [
    {
      "label": "ink label — neutral.50 on neutral.900",
      "on": "primary button (light)",
      "fg": "#f9fafb",
      "bg": "#14171c",
      "ratio": 17.19,
      "grade": "AAA"
    },
    {
      "label": "ink label — neutral.900 on neutral.50",
      "on": "primary button (dark)",
      "fg": "#14171c",
      "bg": "#f9fafb",
      "ratio": 17.19,
      "grade": "AAA"
    },
    {
      "label": "text.primary — neutral.900",
      "on": "light canvas",
      "fg": "#14171c",
      "bg": "#f8fafd",
      "ratio": 17.18,
      "grade": "AAA"
    },
    {
      "label": "text.secondary — neutral.700",
      "on": "light canvas",
      "fg": "#45484c",
      "bg": "#f8fafd",
      "ratio": 8.79,
      "grade": "AAA"
    },
    {
      "label": "text.muted — neutral.600",
      "on": "light canvas",
      "fg": "#5e6165",
      "bg": "#f8fafd",
      "ratio": 5.95,
      "grade": "AA"
    },
    {
      "label": "text.secondary dark — neutral.300",
      "on": "dark canvas",
      "fg": "#d4d6d9",
      "bg": "#15171a",
      "ratio": 12.33,
      "grade": "AAA"
    },
    {
      "label": "accent link — accent.700",
      "on": "light canvas",
      "fg": "#326db5",
      "bg": "#f8fafd",
      "ratio": 5.03,
      "grade": "AA"
    },
    {
      "label": "accent label — neutral.50 on accent.600",
      "on": "accent surface",
      "fg": "#f9fafb",
      "bg": "#4585d5",
      "ratio": 3.61,
      "grade": "AA-large"
    },
    {
      "label": "accent link dark — accent.300",
      "on": "dark canvas",
      "fg": "#a1d6ff",
      "bg": "#15171a",
      "ratio": 11.61,
      "grade": "AAA"
    },
    {
      "label": "danger text — danger.700",
      "on": "light canvas",
      "fg": "#a84b46",
      "bg": "#f8fafd",
      "ratio": 5.34,
      "grade": "AA"
    },
    {
      "label": "danger label — neutral.50 on danger.600",
      "on": "destructive button",
      "fg": "#f9fafb",
      "bg": "#c7605a",
      "ratio": 3.83,
      "grade": "AA-large"
    }
  ],
  "ramps": {
    "neutral": [
      {
        "step": 50,
        "hex": "#f9fafb",
        "onLight": 1,
        "onDark": 17.18
      },
      {
        "step": 100,
        "hex": "#f2f3f5",
        "onLight": 1.06,
        "onDark": 16.17
      },
      {
        "step": 200,
        "hex": "#e5e7e9",
        "onLight": 1.19,
        "onDark": 14.49
      },
      {
        "step": 300,
        "hex": "#d4d6d9",
        "onLight": 1.39,
        "onDark": 12.33
      },
      {
        "step": 400,
        "hex": "#a7a9ad",
        "onLight": 2.25,
        "onDark": 7.63
      },
      {
        "step": 500,
        "hex": "#7d8083",
        "onLight": 3.8,
        "onDark": 4.52
      },
      {
        "step": 600,
        "hex": "#5e6165",
        "onLight": 5.95,
        "onDark": 2.89
      },
      {
        "step": 700,
        "hex": "#45484c",
        "onLight": 8.79,
        "onDark": 1.95
      },
      {
        "step": 800,
        "hex": "#2b2e32",
        "onLight": 13.05,
        "onDark": 1.32
      },
      {
        "step": 900,
        "hex": "#14171c",
        "onLight": 17.18,
        "onDark": 1
      }
    ],
    "accent": [
      {
        "step": 50,
        "hex": "#edfcff",
        "onLight": 1.01,
        "onDark": 17.08
      },
      {
        "step": 100,
        "hex": "#def5ff",
        "onLight": 1.08,
        "onDark": 15.92
      },
      {
        "step": 200,
        "hex": "#c3e9ff",
        "onLight": 1.22,
        "onDark": 14.04
      },
      {
        "step": 300,
        "hex": "#a1d6ff",
        "onLight": 1.48,
        "onDark": 11.61
      },
      {
        "step": 400,
        "hex": "#7cbaff",
        "onLight": 1.95,
        "onDark": 8.83
      },
      {
        "step": 500,
        "hex": "#5b9def",
        "onLight": 2.67,
        "onDark": 6.43
      },
      {
        "step": 600,
        "hex": "#4585d5",
        "onLight": 3.61,
        "onDark": 4.76
      },
      {
        "step": 700,
        "hex": "#326db5",
        "onLight": 5.03,
        "onDark": 3.41
      },
      {
        "step": 800,
        "hex": "#245692",
        "onLight": 7.12,
        "onDark": 2.41
      },
      {
        "step": 900,
        "hex": "#1a3f6d",
        "onLight": 10.17,
        "onDark": 1.69
      }
    ],
    "danger": [
      {
        "step": 50,
        "hex": "#fff3f0",
        "onLight": 1.04,
        "onDark": 16.53
      },
      {
        "step": 100,
        "hex": "#ffe7e3",
        "onLight": 1.13,
        "onDark": 15.21
      },
      {
        "step": 200,
        "hex": "#ffd2cc",
        "onLight": 1.31,
        "onDark": 13.12
      },
      {
        "step": 300,
        "hex": "#ffb7af",
        "onLight": 1.59,
        "onDark": 10.81
      },
      {
        "step": 400,
        "hex": "#fd968e",
        "onLight": 2.02,
        "onDark": 8.49
      },
      {
        "step": 500,
        "hex": "#e2766f",
        "onLight": 2.85,
        "onDark": 6.03
      },
      {
        "step": 600,
        "hex": "#c7605a",
        "onLight": 3.83,
        "onDark": 4.49
      },
      {
        "step": 700,
        "hex": "#a84b46",
        "onLight": 5.34,
        "onDark": 3.22
      },
      {
        "step": 800,
        "hex": "#873936",
        "onLight": 7.53,
        "onDark": 2.28
      },
      {
        "step": 900,
        "hex": "#652927",
        "onLight": 10.57,
        "onDark": 1.62
      }
    ]
  }
} as const

