import type {
  Account,
  AgentDef,
  AgentProposal,
  AgentRunEntry,
  Approval,
  Commitment,
  Contact,
  DigestBundle,
  Message,
  OnboardingScanResult,
  Reminder,
  Signature,
  Thread,
  TodayBrief,
} from './types'

/** The signed-in user — a founder, Revido's ICP. Outbound mail is "from" them. */
export const USER: Contact = {
  name: 'Sam Okafor',
  email: 'sam@brightfoundry.co',
}

export const ACCOUNTS: Account[] = [
  {
    id: 'acct-gmail',
    provider: 'gmail',
    email: 'sam@brightfoundry.co',
    name: 'Sam Okafor',
    syncProgress: 0.78,
    syncLabel: 'Synced 11 of 14 months…',
  },
  {
    id: 'acct-outlook',
    provider: 'outlook',
    email: 'sam.okafor@outlook.com',
    name: 'Sam Okafor',
    syncProgress: 1,
    syncLabel: 'Fully synced',
  },
]

// ---------- Contacts ----------
const c = (name: string, email: string): Contact => ({ name, email })

const john = c('John Rivera', 'john@acmecorp.com')
const priya = c('Priya Nair', 'priya@nimbus.io')
const sarah = c('Sarah Lindqvist', 'sarah@studioloop.com')
const elena = c('Elena Okafor', 'elena.okafor@gmail.com')
const dan = c('Dan Whitfield', 'dan@meridianlabs.com')
const stripe = c('Stripe', 'receipts@stripe.com')
const mercury = c('Mercury', 'notifications@mercury.com')
const quickbooks = c('QuickBooks', 'invoices@quickbooks.com')
const aws = c('AWS Billing', 'no-reply-billing@amazon.com')
const vercel = c('Vercel', 'notifications@vercel.com')
const linear = c('Linear', 'notifications@linear.app')
const github = c('GitHub', 'notifications@github.com')
const morningBrew = c('Morning Brew', 'crew@morningbrew.com')
const lenny = c("Lenny's Newsletter", 'lenny@substack.com')
const hustle = c('The Hustle', 'news@thehustle.co')
const figma = c('Figma', 'team@figma.com')
const notion = c('Notion', 'team@makenotion.com')
const linkedin = c('LinkedIn', 'jobs-noreply@linkedin.com')
const amazon = c('Amazon.com', 'shipment-tracking@amazon.com')
const calendly = c('Marcus Bell', 'marcus@vantagepartners.com')

// ---------- Messages ----------
// Bodies are pre-sanitized HTML, safe to render in a sandboxed iframe.
export const MESSAGES: Message[] = [
  {
    id: 'm-acme-1',
    threadId: 't-acme',
    from: john,
    to: [USER],
    date: '2026-07-15T08:12:00Z',
    text: 'Hi Sam — circling back on the Q3 proposal. The team loved the direction. A couple of open questions before we can sign off…',
    html: `<p>Hi Sam,</p><p>Circling back on the <strong>Q3 proposal</strong> — the team loved the direction. Two things before we can sign off:</p><ol><li>Can you confirm the <strong>$48,000</strong> figure includes the analytics dashboard?</li><li>We'd want kickoff by <strong>July 22</strong>. Doable on your end?</li></ol><p>Happy to hop on a call Thursday if easier.</p><p>Best,<br/>John</p>`,
    unread: true,
    outbound: false,
    attachments: [
      {
        id: 'a1',
        name: 'Q3-Proposal-v3.pdf',
        size: '840 KB',
        mime: 'application/pdf',
        kind: 'pdf',
      },
    ],
  },
  {
    id: 'm-acme-0',
    threadId: 't-acme',
    from: USER,
    to: [john],
    date: '2026-07-12T15:30:00Z',
    text: 'Thanks John — attaching the revised proposal with the dashboard scope broken out. Let me know what you think.',
    html: `<p>Thanks John — attaching the revised proposal with the dashboard scope broken out separately. Let me know what you think.</p><p>— Sam</p>`,
    unread: false,
    outbound: true,
    attachments: [],
  },
  {
    id: 'm-priya-1',
    threadId: 't-priya',
    from: priya,
    to: [USER],
    date: '2026-07-15T07:40:00Z',
    text: "We're looking for someone to build an internal ops tool — saw Brightfoundry's work and thought of you. Budget is flexible for the right partner. Are you taking projects?",
    html: `<p>Hi Sam,</p><p>We're looking for a partner to build an <strong>internal ops tool</strong> (think lightweight CRM + automation). Saw Brightfoundry's work and immediately thought of you.</p><p>Budget is flexible for the right team. Are you taking new projects this quarter?</p><p>— Priya, Nimbus</p>`,
    unread: true,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-sarah-1',
    threadId: 't-sarah',
    from: sarah,
    to: [USER],
    date: '2026-07-14T18:05:00Z',
    text: 'Final logo set is in the shared folder. I included the mono and stacked variants you asked for. Let me know if you want tweaks before Friday.',
    html: `<p>Hey Sam,</p><p>Final logo set is in the shared folder — mono + stacked variants included. Let me know if you want tweaks <strong>before Friday</strong>, otherwise I'll close out the project.</p><p>🎨 Sarah</p>`,
    unread: false,
    outbound: false,
    imagesBlocked: true,
    attachments: [
      {
        id: 'a2',
        name: 'brightfoundry-logo-final.zip',
        size: '4.1 MB',
        mime: 'application/zip',
        kind: 'zip',
      },
    ],
  },
  {
    id: 'm-dan-1',
    threadId: 't-dan',
    from: USER,
    to: [dan],
    date: '2026-07-09T14:00:00Z',
    text: 'Dan — following up on the partnership doc I sent last week. Any thoughts? Happy to adjust the rev-share terms.',
    html: `<p>Dan — following up on the partnership doc I sent last week. Any thoughts? Happy to adjust the rev-share terms if that's the sticking point.</p><p>— Sam</p>`,
    unread: false,
    outbound: true,
    attachments: [],
  },
  {
    id: 'm-elena-1',
    threadId: 't-elena',
    from: elena,
    to: [USER],
    date: '2026-07-14T20:22:00Z',
    text: "Don't forget your dad's birthday is Saturday! Are you still coming for dinner? Let me know how many.",
    html: `<p>Sweetheart — don't forget your dad's birthday is <strong>Saturday</strong>! 🎂 Are you still coming for dinner? Let me know how many so I can plan.</p><p>Love, Mom</p>`,
    unread: true,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-marcus-1',
    threadId: 't-marcus',
    from: calendly,
    to: [USER],
    date: '2026-07-15T06:30:00Z',
    text: "Great chatting yesterday. Can we find 30 minutes next week to go deeper on the integration scope? I'm open Tue/Wed afternoons.",
    html: `<p>Sam — great chatting yesterday.</p><p>Can we find <strong>30 minutes next week</strong> to go deeper on the integration scope? I'm open <strong>Tuesday and Wednesday afternoons</strong>. Send whatever works.</p><p>Marcus<br/>Vantage Partners</p>`,
    unread: true,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-stripe-1',
    threadId: 't-stripe',
    from: stripe,
    to: [USER],
    date: '2026-07-15T02:10:00Z',
    text: 'Your receipt from Brightfoundry LLC — $29.00 paid to OpenRouter.',
    html: `<p>Receipt from <strong>Anthropic</strong></p><p>Amount paid: <strong>$220.00</strong></p><p>Date: July 15, 2026</p><p>This is an automated receipt for your records.</p>`,
    unread: true,
    outbound: false,
    imagesBlocked: true,
    attachments: [
      {
        id: 'a3',
        name: 'receipt-2026-07-15.pdf',
        size: '96 KB',
        mime: 'application/pdf',
        kind: 'pdf',
      },
    ],
  },
  {
    id: 'm-mercury-1',
    threadId: 't-mercury',
    from: mercury,
    to: [USER],
    date: '2026-07-14T13:00:00Z',
    text: 'A payment of $4,800.00 from Acme Corp has cleared into your account.',
    html: `<p>Good news — a payment of <strong>$4,800.00</strong> from <strong>Acme Corp</strong> has cleared into your Mercury account.</p><p>Available balance: $61,240.18</p>`,
    unread: false,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-qb-1',
    threadId: 't-quickbooks',
    from: quickbooks,
    to: [USER],
    date: '2026-07-13T09:00:00Z',
    text: 'Invoice #1042 for $12,500.00 to Meridian Labs is now 6 days overdue.',
    html: `<p>Reminder: <strong>Invoice #1042</strong> for <strong>$12,500.00</strong> to Meridian Labs is now <strong>6 days overdue</strong>.</p><p>You can send a reminder from your dashboard.</p>`,
    unread: true,
    outbound: false,
    attachments: [
      { id: 'a4', name: 'invoice-1042.pdf', size: '112 KB', mime: 'application/pdf', kind: 'pdf' },
    ],
  },
  {
    id: 'm-aws-1',
    threadId: 't-aws',
    from: aws,
    to: [USER],
    date: '2026-07-14T05:00:00Z',
    text: 'Your AWS estimated bill for July is $342.19 so far.',
    html: `<p>Your AWS estimated bill for <strong>July 2026</strong> is <strong>$342.19</strong> so far. This is an automated notification.</p>`,
    unread: false,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-vercel-1',
    threadId: 't-vercel',
    from: vercel,
    to: [USER],
    date: '2026-07-15T04:45:00Z',
    text: 'Deployment to production succeeded for brightfoundry-web (main).',
    html: `<p>✅ Deployment to <strong>production</strong> succeeded for <code>brightfoundry-web</code> (main @ 3f9a2c1).</p><p>Duration: 47s.</p>`,
    unread: false,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-linear-1',
    threadId: 't-linear',
    from: linear,
    to: [USER],
    date: '2026-07-14T22:15:00Z',
    text: 'Priya assigned you BRI-238 "Draft ops-tool scoping doc".',
    html: `<p><strong>Priya</strong> assigned you <strong>BRI-238</strong> — "Draft ops-tool scoping doc". Due in 3 days.</p>`,
    unread: true,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-github-1',
    threadId: 't-github',
    from: github,
    to: [USER],
    date: '2026-07-15T01:20:00Z',
    text: '[brightfoundry/app] PR #211 approved by 1 reviewer.',
    html: `<p><strong>PR #211</strong> "Add invoice export" was approved and is ready to merge.</p>`,
    unread: false,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-brew-1',
    threadId: 't-brew',
    from: morningBrew,
    to: [USER],
    date: '2026-07-15T09:30:00Z',
    text: "☕ Markets wobble, a new AI unicorn, and why everyone's talking about 'quiet vacationing'.",
    html: `<p>☕️ <strong>Good morning.</strong> Markets wobbled, another AI startup hit unicorn status, and everyone's suddenly talking about "quiet vacationing." Here's what you need to know…</p>`,
    unread: true,
    outbound: false,
    imagesBlocked: true,
    attachments: [],
  },
  {
    id: 'm-lenny-1',
    threadId: 't-lenny',
    from: lenny,
    to: [USER],
    date: '2026-07-14T11:00:00Z',
    text: 'How the best founders run their week — a system for ruthless prioritization.',
    html: `<p>This week: a system for ruthless prioritization used by three founders who scaled past $50M ARR. Plus the one meeting they all kill first.</p>`,
    unread: true,
    outbound: false,
    imagesBlocked: true,
    attachments: [],
  },
  {
    id: 'm-hustle-1',
    threadId: 't-hustle',
    from: hustle,
    to: [USER],
    date: '2026-07-15T10:00:00Z',
    text: 'The unglamorous business quietly printing money in the suburbs.',
    html: `<p>Today: the unglamorous suburban business quietly printing money, and why a 100-year-old brand just went viral on TikTok.</p>`,
    unread: true,
    outbound: false,
    imagesBlocked: true,
    attachments: [],
  },
  {
    id: 'm-figma-1',
    threadId: 't-figma',
    from: figma,
    to: [USER],
    date: '2026-07-13T16:00:00Z',
    text: 'Sarah commented on "Brightfoundry Brand": "Updated the mono variant — take a look!"',
    html: `<p><strong>Sarah</strong> commented on <em>Brightfoundry Brand</em>: "Updated the mono variant — take a look!"</p>`,
    unread: false,
    outbound: false,
    attachments: [],
  },
  {
    id: 'm-notion-1',
    threadId: 't-notion',
    from: notion,
    to: [USER],
    date: '2026-07-12T12:00:00Z',
    text: 'Your weekly digest: 3 pages edited, 2 comments waiting.',
    html: `<p>Your Notion weekly digest: <strong>3 pages</strong> edited, <strong>2 comments</strong> waiting for you.</p>`,
    unread: false,
    outbound: false,
    imagesBlocked: true,
    attachments: [],
  },
  {
    id: 'm-linkedin-1',
    threadId: 't-linkedin',
    from: linkedin,
    to: [USER],
    date: '2026-07-14T08:00:00Z',
    text: 'Sam, 12 new jobs match "Founder / Technical" in your network.',
    html: `<p>Sam, <strong>12 new opportunities</strong> match your interests this week. See who's hiring in your network.</p>`,
    unread: false,
    outbound: false,
    imagesBlocked: true,
    attachments: [],
  },
  {
    id: 'm-amazon-1',
    threadId: 't-amazon',
    from: amazon,
    to: [USER],
    date: '2026-07-14T19:30:00Z',
    text: 'Your package with USB-C hub is arriving Thursday, July 18. Track: 1Z999AA10123456784.',
    html: `<p>Your order is on the way! 📦</p><p>"Anker USB-C Hub, 7-in-1" is arriving <strong>Thursday, July 18</strong>.</p><p>Tracking: <strong>1Z999AA10123456784</strong></p>`,
    unread: false,
    outbound: false,
    imagesBlocked: true,
    attachments: [],
  },
]

// ---------- Threads ----------
export const THREADS: Thread[] = [
  {
    id: 't-acme',
    accountId: 'acct-gmail',
    subject: 'Q3 proposal — a couple of open questions',
    participants: [john, USER],
    category: 'to-reply',
    priority: 'urgent',
    priorityScore: 96,
    tldr: 'John approved the direction; needs the $48k scope + a July 22 kickoff confirmed.',
    summary:
      'John at Acme loves the Q3 proposal and is ready to sign off. He needs two confirmations: that the $48,000 price includes the analytics dashboard, and that you can kick off by July 22. He offered a Thursday call.',
    unread: true,
    starred: true,
    snoozedUntil: null,
    hasAttachments: true,
    badges: [
      { kind: 'amount', label: '$48,000' },
      { kind: 'date', label: 'Jul 22' },
      { kind: 'attachment', label: '1' },
    ],
    extracted: [
      { type: 'amount', label: 'Proposal value', value: '$48,000' },
      { type: 'date', label: 'Requested kickoff', value: 'Jul 22, 2026' },
      { type: 'action', label: 'Confirm dashboard is in scope', value: '', done: false },
      { type: 'action', label: 'Confirm July 22 kickoff', value: '', done: false },
    ],
    messageIds: ['m-acme-0', 'm-acme-1'],
    lastMessageAt: '2026-07-15T08:12:00Z',
    awaitingReply: false,
    labels: ['Clients', 'Acme'],
  },
  {
    id: 't-priya',
    accountId: 'acct-gmail',
    subject: 'New project — internal ops tool',
    participants: [priya, USER],
    category: 'to-reply',
    priority: 'high',
    priorityScore: 89,
    tldr: 'Warm inbound lead: Nimbus wants an internal ops tool, budget flexible.',
    summary:
      'Priya from Nimbus found Brightfoundry and wants a partner to build an internal ops tool (CRM + automation). Budget is flexible. She asks if you are taking projects this quarter — a warm lead worth a fast reply.',
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'people', label: 'New lead' }],
    extracted: [
      { type: 'action', label: 'Reply — are you taking projects?', value: '', done: false },
      { type: 'contact', label: 'Priya Nair', value: 'priya@nimbus.io' },
    ],
    messageIds: ['m-priya-1'],
    lastMessageAt: '2026-07-15T07:40:00Z',
    awaitingReply: false,
    labels: ['Leads'],
  },
  {
    id: 't-marcus',
    accountId: 'acct-gmail',
    subject: 'Next steps — integration scope',
    participants: [calendly, USER],
    category: 'to-reply',
    priority: 'high',
    priorityScore: 82,
    tldr: 'Marcus wants to book 30 min next week (Tue/Wed PM) on integration scope.',
    summary:
      'Marcus at Vantage wants a 30-minute call next week to go deeper on integration scope. He is open Tuesday and Wednesday afternoons and asked you to send a time.',
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'date', label: 'Next week' }],
    extracted: [
      { type: 'action', label: 'Send a Tue/Wed PM slot', value: '', done: false },
      { type: 'date', label: 'Availability', value: 'Tue/Wed afternoon' },
    ],
    messageIds: ['m-marcus-1'],
    lastMessageAt: '2026-07-15T06:30:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-sarah',
    accountId: 'acct-gmail',
    subject: 'Final logo set delivered 🎨',
    participants: [sarah, USER],
    category: 'to-reply',
    priority: 'normal',
    priorityScore: 61,
    tldr: 'Sarah delivered the final logos; wants tweaks flagged before Friday.',
    summary:
      'Sarah delivered the final logo set (mono + stacked variants) in the shared folder. She wants any tweaks flagged before Friday, otherwise she closes out the project.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: true,
    badges: [
      { kind: 'attachment', label: '1' },
      { kind: 'date', label: 'Fri' },
    ],
    extracted: [
      { type: 'date', label: 'Tweaks deadline', value: 'Friday, Jul 17' },
      { type: 'action', label: 'Review logo set', value: '', done: false },
    ],
    messageIds: ['m-sarah-1'],
    lastMessageAt: '2026-07-14T18:05:00Z',
    awaitingReply: false,
    labels: ['Design'],
  },
  {
    id: 't-elena',
    accountId: 'acct-gmail',
    subject: "Dad's birthday Saturday 🎂",
    participants: [elena, USER],
    category: 'personal',
    priority: 'high',
    priorityScore: 74,
    tldr: 'Mom: confirm dinner headcount for Dad’s birthday Saturday.',
    summary:
      "Your mom is reminding you that your dad's birthday is Saturday and asking whether you're coming to dinner, and for how many people.",
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'date', label: 'Sat' }],
    extracted: [
      { type: 'date', label: "Dad's birthday", value: 'Saturday, Jul 18' },
      { type: 'action', label: 'Reply with headcount', value: '', done: false },
    ],
    messageIds: ['m-elena-1'],
    lastMessageAt: '2026-07-14T20:22:00Z',
    awaitingReply: false,
    labels: ['Family'],
  },
  {
    id: 't-dan',
    accountId: 'acct-gmail',
    subject: 'Partnership doc — following up',
    participants: [USER, dan],
    category: 'awaiting-reply',
    priority: 'normal',
    priorityScore: 58,
    tldr: 'You followed up 6 days ago on the partnership doc — still no reply from Dan.',
    summary:
      'You sent Dan a partnership doc and followed up on July 9 offering to adjust rev-share terms. He has not replied in 6 days — a good candidate for a nudge.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'people', label: 'No reply 6d' }],
    extracted: [{ type: 'action', label: 'Chase Dan', value: '', done: false }],
    messageIds: ['m-dan-1'],
    lastMessageAt: '2026-07-09T14:00:00Z',
    awaitingReply: true,
    labels: ['Partnerships'],
  },
  {
    id: 't-quickbooks',
    accountId: 'acct-gmail',
    subject: 'Invoice #1042 is 6 days overdue',
    participants: [quickbooks, USER],
    category: 'receipts',
    priority: 'high',
    priorityScore: 71,
    tldr: 'Meridian Labs invoice for $12,500 is 6 days overdue.',
    summary:
      'QuickBooks flags that Invoice #1042 for $12,500 to Meridian Labs is 6 days overdue. You may want to send a reminder.',
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: true,
    badges: [
      { kind: 'amount', label: '$12,500' },
      { kind: 'attachment', label: '1' },
    ],
    extracted: [
      { type: 'amount', label: 'Overdue invoice', value: '$12,500' },
      { type: 'date', label: 'Due date passed', value: 'Jul 9' },
    ],
    messageIds: ['m-qb-1'],
    lastMessageAt: '2026-07-13T09:00:00Z',
    awaitingReply: false,
    labels: ['Finance'],
  },
  {
    id: 't-stripe',
    accountId: 'acct-gmail',
    subject: 'Your receipt from Anthropic — $220.00',
    participants: [stripe, USER],
    category: 'receipts',
    priority: 'low',
    priorityScore: 20,
    tldr: 'Receipt: $220.00 to Anthropic for July API usage.',
    summary: 'A Stripe receipt for $220.00 paid to Anthropic for July API usage.',
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: true,
    badges: [
      { kind: 'amount', label: '$220.00' },
      { kind: 'attachment', label: '1' },
    ],
    extracted: [{ type: 'amount', label: 'Charged', value: '$220.00' }],
    messageIds: ['m-stripe-1'],
    lastMessageAt: '2026-07-15T02:10:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-mercury',
    accountId: 'acct-gmail',
    subject: '$4,800 from Acme Corp has cleared',
    participants: [mercury, USER],
    category: 'notifications',
    priority: 'normal',
    priorityScore: 44,
    tldr: 'Payment of $4,800 from Acme Corp cleared into Mercury.',
    summary:
      'Mercury notified you that a $4,800 payment from Acme Corp has cleared. Balance $61,240.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'amount', label: '$4,800' }],
    extracted: [{ type: 'amount', label: 'Payment received', value: '$4,800' }],
    messageIds: ['m-mercury-1'],
    lastMessageAt: '2026-07-14T13:00:00Z',
    awaitingReply: false,
    labels: ['Finance'],
  },
  {
    id: 't-aws',
    accountId: 'acct-gmail',
    subject: 'AWS estimated bill: $342.19',
    participants: [aws, USER],
    category: 'notifications',
    priority: 'low',
    priorityScore: 18,
    tldr: 'AWS July estimate is $342.19 so far.',
    summary: 'AWS estimated your July bill at $342.19 so far.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'amount', label: '$342.19' }],
    extracted: [{ type: 'amount', label: 'Estimated bill', value: '$342.19' }],
    messageIds: ['m-aws-1'],
    lastMessageAt: '2026-07-14T05:00:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-vercel',
    accountId: 'acct-gmail',
    subject: 'Production deploy succeeded — brightfoundry-web',
    participants: [vercel, USER],
    category: 'notifications',
    priority: 'low',
    priorityScore: 12,
    tldr: 'Production deploy of brightfoundry-web succeeded in 47s.',
    summary: 'Vercel reports a successful production deployment of brightfoundry-web (main).',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [],
    messageIds: ['m-vercel-1'],
    lastMessageAt: '2026-07-15T04:45:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-linear',
    accountId: 'acct-gmail',
    subject: 'Priya assigned you BRI-238',
    participants: [linear, USER],
    category: 'notifications',
    priority: 'normal',
    priorityScore: 40,
    tldr: 'New Linear task BRI-238 "Draft ops-tool scoping doc", due in 3 days.',
    summary:
      'Linear notification: Priya assigned you BRI-238, "Draft ops-tool scoping doc", due in 3 days.',
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [{ kind: 'date', label: '3 days' }],
    extracted: [{ type: 'date', label: 'Task due', value: 'Jul 17' }],
    messageIds: ['m-linear-1'],
    lastMessageAt: '2026-07-14T22:15:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-github',
    accountId: 'acct-gmail',
    subject: 'PR #211 approved',
    participants: [github, USER],
    category: 'notifications',
    priority: 'low',
    priorityScore: 22,
    tldr: 'PR #211 "Add invoice export" approved and ready to merge.',
    summary: 'GitHub: PR #211 was approved by a reviewer and is ready to merge.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [],
    messageIds: ['m-github-1'],
    lastMessageAt: '2026-07-15T01:20:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-brew',
    accountId: 'acct-gmail',
    subject: '☕ Markets wobble & a new AI unicorn',
    participants: [morningBrew, USER],
    category: 'newsletters',
    priority: 'low',
    priorityScore: 15,
    tldr: 'Morning Brew: markets, a new AI unicorn, and "quiet vacationing".',
    summary:
      "Morning Brew's daily: market wobble, a fresh AI unicorn, and the rise of 'quiet vacationing'.",
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [{ type: 'link', label: 'Unsubscribe', value: 'Unsubscribe', href: '#' }],
    messageIds: ['m-brew-1'],
    lastMessageAt: '2026-07-15T09:30:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-lenny',
    accountId: 'acct-gmail',
    subject: 'How the best founders run their week',
    participants: [lenny, USER],
    category: 'newsletters',
    priority: 'low',
    priorityScore: 24,
    tldr: "Lenny's Newsletter: a ruthless-prioritization system from $50M+ founders.",
    summary:
      "Lenny's Newsletter shares a prioritization system used by founders who scaled past $50M ARR.",
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [{ type: 'link', label: 'Unsubscribe', value: 'Unsubscribe', href: '#' }],
    messageIds: ['m-lenny-1'],
    lastMessageAt: '2026-07-14T11:00:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-hustle',
    accountId: 'acct-gmail',
    subject: 'The suburban business printing money',
    participants: [hustle, USER],
    category: 'newsletters',
    priority: 'low',
    priorityScore: 11,
    tldr: 'The Hustle: an unglamorous suburban business quietly printing money.',
    summary:
      'The Hustle covers a low-key suburban business making surprising margins, plus a viral heritage brand.',
    unread: true,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [{ type: 'link', label: 'Unsubscribe', value: 'Unsubscribe', href: '#' }],
    messageIds: ['m-hustle-1'],
    lastMessageAt: '2026-07-15T10:00:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-figma',
    accountId: 'acct-gmail',
    subject: 'Sarah commented on Brightfoundry Brand',
    participants: [figma, USER],
    category: 'notifications',
    priority: 'low',
    priorityScore: 28,
    tldr: 'Figma: Sarah updated & commented on the mono logo variant.',
    summary:
      'Figma notification that Sarah commented on the Brightfoundry Brand file about the mono variant.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [],
    messageIds: ['m-figma-1'],
    lastMessageAt: '2026-07-13T16:00:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-notion',
    accountId: 'acct-outlook',
    subject: 'Your Notion weekly digest',
    participants: [notion, USER],
    category: 'newsletters',
    priority: 'low',
    priorityScore: 9,
    tldr: 'Notion weekly: 3 pages edited, 2 comments waiting.',
    summary: 'Notion weekly digest: 3 pages edited and 2 comments waiting.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [{ type: 'link', label: 'Unsubscribe', value: 'Unsubscribe', href: '#' }],
    messageIds: ['m-notion-1'],
    lastMessageAt: '2026-07-12T12:00:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-linkedin',
    accountId: 'acct-gmail',
    subject: '12 new jobs match your interests',
    participants: [linkedin, USER],
    category: 'promotions',
    priority: 'low',
    priorityScore: 6,
    tldr: 'LinkedIn: 12 new "Founder / Technical" roles in your network.',
    summary: 'LinkedIn promo: 12 new opportunities matching your interests this week.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [],
    extracted: [{ type: 'link', label: 'Unsubscribe', value: 'Unsubscribe', href: '#' }],
    messageIds: ['m-linkedin-1'],
    lastMessageAt: '2026-07-14T08:00:00Z',
    awaitingReply: false,
    labels: [],
  },
  {
    id: 't-amazon',
    accountId: 'acct-gmail',
    subject: 'Your package is arriving Thursday',
    participants: [amazon, USER],
    category: 'notifications',
    priority: 'low',
    priorityScore: 30,
    tldr: 'Amazon: USB-C hub arriving Thu Jul 18 — tracking 1Z999AA10123456784.',
    summary:
      'Amazon shipment update: your USB-C hub arrives Thursday, July 18. A tracking number is available.',
    unread: false,
    starred: false,
    snoozedUntil: null,
    hasAttachments: false,
    badges: [
      { kind: 'date', label: 'Thu' },
      { kind: 'tracking', label: 'Track' },
    ],
    extracted: [
      { type: 'date', label: 'Arriving', value: 'Thu, Jul 18' },
      { type: 'tracking', label: 'Tracking #', value: '1Z999AA10123456784', href: '#' },
    ],
    messageIds: ['m-amazon-1'],
    lastMessageAt: '2026-07-14T19:30:00Z',
    awaitingReply: false,
    labels: [],
  },
]

// ---------- Agents ----------
export const AGENTS: AgentDef[] = [
  {
    id: 'ag-unsub',
    name: 'Unsubscriber',
    description: 'Finds newsletters you never open and queues one-tap unsubscribes.',
    icon: 'MailX',
    enabled: false,
    trigger: 'Weekly sweep, Sundays 8pm',
    conditions: ['Category is Newsletters or Promotions', 'Not opened in 30+ days'],
    actions: [
      { type: 'unsubscribe', label: 'Unsubscribe', needsApproval: true },
      { type: 'archive', label: 'Archive', needsApproval: false },
    ],
    runCount: 0,
    affectedCount: 0,
    prebuilt: true,
    accent: 'promotions',
  },
  {
    id: 'ag-chaser',
    name: 'Follow-up Chaser',
    description: 'Nudges people who never replied to your important sent mail.',
    icon: 'Send',
    enabled: true,
    trigger: 'Nightly at 9pm',
    conditions: ['Sent by you', 'No reply in 4+ days', 'Was a question or ask'],
    actions: [
      { type: 'draft', label: 'Draft chaser', needsApproval: false },
      { type: 'send', label: 'Send chaser', needsApproval: true },
    ],
    runCount: 37,
    affectedCount: 12,
    prebuilt: true,
    accent: 'awaiting-reply',
  },
  {
    id: 'ag-invoice',
    name: 'Invoice Filer',
    description: 'Labels invoices & receipts, extracts amounts, files them by month.',
    icon: 'Receipt',
    enabled: true,
    trigger: 'New mail arrives',
    conditions: ['Contains invoice or receipt', 'Has an amount'],
    actions: [
      { type: 'label', label: 'Label Receipts', needsApproval: false },
      { type: 'file', label: 'File by month', needsApproval: false },
    ],
    runCount: 214,
    affectedCount: 63,
    prebuilt: true,
    accent: 'receipts',
  },
  {
    id: 'ag-digest',
    name: 'Newsletter Digester',
    description: 'Bundles low-value mail into one clean daily digest.',
    icon: 'Newspaper',
    enabled: true,
    trigger: 'Daily at 7am',
    conditions: ['Category is Newsletters', 'Priority is low'],
    actions: [
      { type: 'bundle', label: 'Bundle into digest', needsApproval: false },
      { type: 'archive', label: 'Archive originals', needsApproval: false },
    ],
    runCount: 92,
    affectedCount: 34,
    prebuilt: true,
    accent: 'newsletters',
  },
  {
    id: 'ag-receipt',
    name: 'Receipt Collector',
    description: 'Forwards every receipt to your accounting inbox at month end.',
    icon: 'FolderInput',
    enabled: false,
    trigger: 'Monthly, last day',
    conditions: ['Category is Receipts'],
    actions: [{ type: 'forward', label: 'Forward to accounting', needsApproval: true }],
    runCount: 0,
    affectedCount: 0,
    prebuilt: true,
    accent: 'receipts',
  },
  {
    id: 'ag-meeting',
    name: 'Meeting Prep',
    description: 'Before each meeting, drafts a brief from your recent threads with attendees.',
    icon: 'CalendarClock',
    enabled: false,
    trigger: '30 min before calendar events',
    conditions: ['Event has external attendees'],
    actions: [{ type: 'draft', label: 'Draft prep brief', needsApproval: false }],
    runCount: 0,
    affectedCount: 0,
    prebuilt: true,
    accent: 'calendar',
  },
]

export const AGENT_RUNS: AgentRunEntry[] = [
  {
    id: 'run-1',
    agentId: 'ag-digest',
    agentName: 'Newsletter Digester',
    agentIcon: 'Newspaper',
    at: '2026-07-15T07:00:00Z',
    summary: 'Bundled 6 newsletters into your morning digest and archived the originals.',
    reasoning:
      'These 6 messages are from known newsletter senders you open less than 10% of the time. Bundling keeps the inbox clear while preserving the content in one place.',
    affected: [
      {
        threadId: 't-brew',
        subject: '☕ Markets wobble & a new AI unicorn',
        sender: 'Morning Brew',
      },
      {
        threadId: 't-lenny',
        subject: 'How the best founders run their week',
        sender: "Lenny's Newsletter",
      },
      {
        threadId: 't-hustle',
        subject: 'The suburban business printing money',
        sender: 'The Hustle',
      },
      { threadId: 't-notion', subject: 'Your Notion weekly digest', sender: 'Notion' },
    ],
    status: 'done',
    reversible: true,
  },
  {
    id: 'run-2',
    agentId: 'ag-invoice',
    agentName: 'Invoice Filer',
    agentIcon: 'Receipt',
    at: '2026-07-15T02:11:00Z',
    summary: 'Labeled 2 receipts and filed them under July 2026.',
    reasoning:
      'Both messages contain a payment amount and originate from known billing senders (Stripe, QuickBooks). Filed by the month of the charge date.',
    affected: [
      { threadId: 't-stripe', subject: 'Your receipt from Anthropic — $220.00', sender: 'Stripe' },
      {
        threadId: 't-quickbooks',
        subject: 'Invoice #1042 is 6 days overdue',
        sender: 'QuickBooks',
      },
    ],
    status: 'done',
    reversible: true,
  },
  {
    id: 'run-3',
    agentId: 'ag-chaser',
    agentName: 'Follow-up Chaser',
    agentIcon: 'Send',
    at: '2026-07-15T09:00:00Z',
    summary: 'Drafted a chaser to Dan Whitfield (partnership doc, no reply in 6 days).',
    reasoning:
      'You sent Dan a partnership doc and followed up on Jul 9. It contained an explicit ask and has had no reply for 6 days, past your 4-day threshold. Drafted a gentle nudge for your approval before sending.',
    affected: [
      { threadId: 't-dan', subject: 'Partnership doc — following up', sender: 'Dan Whitfield' },
    ],
    status: 'pending-approval',
    reversible: false,
  },
  {
    id: 'run-4',
    agentId: 'ag-invoice',
    agentName: 'Invoice Filer',
    agentIcon: 'Receipt',
    at: '2026-07-14T05:01:00Z',
    summary: 'Labeled the AWS billing notice and extracted $342.19.',
    reasoning: 'AWS billing sender with an amount present; labeled Receipts and filed under July.',
    affected: [
      { threadId: 't-aws', subject: 'AWS estimated bill: $342.19', sender: 'AWS Billing' },
    ],
    status: 'done',
    reversible: true,
  },
]

export const APPROVALS: Approval[] = [
  {
    id: 'appr-1',
    agentId: 'ag-chaser',
    agentName: 'Follow-up Chaser',
    agentIcon: 'Send',
    action: 'Send chaser email',
    threadId: 't-dan',
    subject: 'Partnership doc — following up',
    sender: 'Dan Whitfield',
    preview:
      'Hi Dan — just floating this back to the top of your inbox. No rush, but happy to jump on a quick call if the rev-share terms are the sticking point. Would love to find a shape that works for both of us.',
    createdAt: '2026-07-15T09:00:00Z',
  },
  {
    id: 'appr-2',
    agentId: 'ag-unsub',
    agentName: 'Unsubscriber',
    agentIcon: 'MailX',
    action: 'Unsubscribe from 3 senders',
    threadId: 't-linkedin',
    subject: 'LinkedIn, RetailMeNot, Groupon',
    sender: '3 senders',
    preview:
      'Unsubscribe from LinkedIn Jobs, RetailMeNot, and Groupon — none opened in 60+ days. Links verified as one-click unsubscribe.',
    createdAt: '2026-07-15T08:00:00Z',
  },
]

// ---------- Reminders / commitments ----------
export const REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    kind: 'follow-up',
    threadId: 't-dan',
    subject: 'Partnership doc — following up',
    context: 'You sent this 6 days ago. No reply from Dan.',
    sender: 'Dan Whitfield',
    dueAt: '2026-07-15T09:00:00Z',
    draftReply:
      "Hi Dan — just floating this back up. Happy to adjust the rev-share terms if that's the sticking point. Would a 15-min call this week help?",
  },
  {
    id: 'rem-2',
    kind: 'deadline',
    threadId: 't-acme',
    subject: 'Q3 proposal — kickoff by July 22',
    context: 'Acme wants kickoff confirmed by July 22.',
    sender: 'John Rivera',
    dueAt: '2026-07-22T09:00:00Z',
  },
  {
    id: 'rem-3',
    kind: 'deadline',
    threadId: 't-sarah',
    subject: 'Flag logo tweaks before Friday',
    context: 'Sarah closes the project Friday if no tweaks.',
    sender: 'Sarah Lindqvist',
    dueAt: '2026-07-17T17:00:00Z',
  },
  {
    id: 'rem-4',
    kind: 'follow-up',
    threadId: 't-quickbooks',
    subject: 'Chase Meridian Labs on invoice #1042',
    context: 'Invoice is 6 days overdue.',
    sender: 'Meridian Labs',
    dueAt: '2026-07-16T09:00:00Z',
    draftReply:
      'Hi — a friendly reminder that invoice #1042 ($12,500) is now past due. Could you let me know the expected payment date? Thanks!',
  },
  {
    id: 'rem-5',
    kind: 'snoozed',
    threadId: 't-linear',
    subject: 'Draft ops-tool scoping doc (BRI-238)',
    context: 'Snoozed to tomorrow morning.',
    sender: 'Linear',
    dueAt: '2026-07-16T08:00:00Z',
  },
]

export const COMMITMENTS: Commitment[] = [
  {
    id: 'com-1',
    text: "You told John you'd confirm the dashboard scope by end of week.",
    threadId: 't-acme',
    subject: 'Q3 proposal',
    counterpart: 'John Rivera',
    dueAt: '2026-07-17T17:00:00Z',
  },
  {
    id: 'com-2',
    text: 'You promised Marcus a Tue/Wed slot for the integration call.',
    threadId: 't-marcus',
    subject: 'Next steps — integration scope',
    counterpart: 'Marcus Bell',
    dueAt: '2026-07-16T12:00:00Z',
  },
  {
    id: 'com-3',
    text: "You said you'd send Priya availability this week.",
    threadId: 't-priya',
    subject: 'New project — internal ops tool',
    counterpart: 'Priya Nair',
    dueAt: '2026-07-18T17:00:00Z',
  },
]

// ---------- Today / digest ----------
export const CAN_IGNORE: DigestBundle[] = [
  {
    category: 'newsletters',
    count: 4,
    items: [
      { subject: '☕ Markets wobble & a new AI unicorn', sender: 'Morning Brew' },
      { subject: 'How the best founders run their week', sender: "Lenny's Newsletter" },
      { subject: 'The suburban business printing money', sender: 'The Hustle' },
      { subject: 'Your Notion weekly digest', sender: 'Notion' },
    ],
  },
  {
    category: 'notifications',
    count: 3,
    items: [
      { subject: 'Production deploy succeeded', sender: 'Vercel' },
      { subject: 'PR #211 approved', sender: 'GitHub' },
      { subject: 'Sarah commented on Brightfoundry Brand', sender: 'Figma' },
    ],
  },
  {
    category: 'promotions',
    count: 1,
    items: [{ subject: '12 new jobs match your interests', sender: 'LinkedIn' }],
  },
]

export const TODAY_BRIEF: TodayBrief = {
  greeting: 'Good morning, Sam',
  date: 'Wednesday, July 15',
  stats: { needYou: 6, promises: 3, agentsHandled: 24 },
  needsYou: ['t-acme', 't-priya', 't-marcus', 't-elena', 't-quickbooks'],
  commitments: ['com-1', 'com-2', 'com-3'],
  agentReport: ['run-1', 'run-2', 'run-3'],
  canIgnore: CAN_IGNORE,
  revidoCta:
    'This brief saved you about 20 minutes. Want agents like these built for your whole team’s workflows?',
}

// ---------- Onboarding ----------
export const AGENT_PROPOSALS: AgentProposal[] = [
  {
    id: 'prop-digest',
    title: 'Bundle your newsletters',
    detail: 'We found 34 newsletters clogging your inbox. Bundle them into one daily digest?',
    icon: 'Newspaper',
    accent: 'newsletters',
    metric: '34 newsletters',
  },
  {
    id: 'prop-chaser',
    title: 'Chase your no-replies',
    detail: '4 emails you sent never got a reply. Want a nightly agent to nudge them for you?',
    icon: 'Send',
    accent: 'awaiting-reply',
    metric: '4 awaiting reply',
  },
  {
    id: 'prop-invoice',
    title: 'Auto-file your invoices',
    detail: 'You get invoices from 7 vendors. Auto-label, extract amounts, and file them by month?',
    icon: 'Receipt',
    accent: 'receipts',
    metric: '7 vendors',
  },
]

export const ONBOARDING_SCAN: OnboardingScanResult = {
  totalThreads: 1284,
  needReplies: 12,
  newsletters: 34,
  invoices: 3,
  awaitingReply: 4,
  proposals: AGENT_PROPOSALS,
}

export const SIGNATURES: Signature[] = [
  {
    id: 'sig-1',
    accountId: 'acct-gmail',
    name: 'Default',
    html: '<p>Sam Okafor<br/>Founder, Brightfoundry<br/>brightfoundry.co</p>',
  },
]

/** Rotating Revido CTA lines used across wow-moment surfaces. */
export const REVIDO_CTAS: string[] = [
  'Want agents like this built for your company? Talk to Revido →',
  'This is what custom AI tooling feels like. We build it for teams → Talk to Revido',
  'Loved that? Revido builds bespoke AI tools for companies like yours →',
]
